name       : haskell-streaming-commons
version    : 0.1.17
release    : 1
source     :
    - http://hackage.haskell.org/package/streaming-commons-0.1.17/streaming-commons-0.1.17.tar.gz : e50a38cb8b626ef2f031c195e22171ffce00e20cbe63e8c768887564a7f47da9
license    : MIT
component  : programming.haskell
summary    : Provides low-dependency functionality commonly needed by various streaming data libraries, such as conduit and pipes. 
description: |
    Provides low-dependency functionality commonly needed by various streaming data libraries, such as conduit and pipes. 
builddeps  :
    - haskell-cabal-install
    - haskell-blaze-builder
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
