name       : haskell-streaming-commons
version    : 0.2.0.0
release    : 2
source     :
    - https://hackage.haskell.org/package/streaming-commons-0.2.0.0/streaming-commons-0.2.0.0.tar.gz : f4e2b8460325c133c83d04048e334fb502ba3627f41ffc85c05f81f1f38ace5f
license    : MIT
component  : programming.haskell
summary    : Provides low-dependency functionality commonly needed by various streaming data libraries, such as conduit and pipes.
description: "Provides low-dependency functionality commonly needed by various streaming data libraries, such as conduit and pipes. \n"
builddeps  :
    - haskell-async
    - haskell-cabal-install
    - haskell-blaze-builder
    - haskell-network
    - haskell-random
    - haskell-stm
    - haskell-zlib
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
