name       : haskell-streaming-commons
version    : 0.2.1.2
release    : 3
source     :
    - https://hackage.haskell.org/package/streaming-commons-0.2.1.2/streaming-commons-0.2.1.2.tar.gz : ea2a6d4b2dfabe8cdf3b4e0a29db9b14170f59d3554b70e0377779867efcfc16
license    : MIT
component  : programming.haskell
summary    : Provides low-dependency functionality commonly needed by various streaming data libraries, such as conduit and pipes.
description: |
    Provides low-dependency functionality commonly needed by various streaming data libraries, such as conduit and pipes.
builddeps  :
    - ghc-devel
    - haskell-async-devel
    - haskell-cabal-install
    - haskell-blaze-builder-devel
    - haskell-network-devel
    - haskell-random-devel
    - haskell-zlib-devel
rundeps    :
    - devel:
        - haskell-async-devel
        - haskell-cabal-install
        - haskell-blaze-builder-devel
        - haskell-network-devel
        - haskell-random-devel
        - haskell-zlib-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
